# Generated by Django 5.0.6 on 2024-07-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_booking_schedule_remove_booking_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
