# Generated by Django 5.0.6 on 2024-07-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='City', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Country', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(default='House number', max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='State', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='Street name', max_length=255),
        ),
    ]
