# Generated by Django 5.0.6 on 2024-07-16 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_message_poster'),
        ('main', '0004_alter_address_house_number'),
        ('transaction', '0003_alter_booking_message_poster'),
        ('user', '0004_messageposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='message_poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='user.messageposter'),
        ),
        migrations.DeleteModel(
            name='MessagePoster',
        ),
    ]
