# Generated by Django 5.0.6 on 2024-07-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
