# Generated by Django 5.0.6 on 2024-07-15 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_media_gofer_media_vendor_alter_media_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progofer',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='progofer',
            name='custom_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_gofer', to=settings.AUTH_USER_MODEL),
        ),
    ]
