# Generated by Django 5.0.6 on 2024-07-17 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_messageposter'),
    ]

    operations = [
        migrations.AddField(
            model_name='progofer',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week_available', models.CharField(choices=[('mon', 'Monday'), ('tues', 'Tuesday'), ('wed', 'Wednesday'), ('thur', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=10)),
                ('start_time_available', models.TimeField()),
                ('end_time_available', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pro_gofer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='user.progofer')),
            ],
        ),
    ]
