# Generated by Django 5.0.6 on 2024-07-18 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_progofer_is_available_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_created', to='user.messageposter')),
                ('pro_gofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='user.progofer')),
            ],
        ),
    ]
