# Generated by Django 5.0.6 on 2024-07-18 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_booking_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='pro_gofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='user.progofer'),
        ),
    ]
